version: "2"

run:
  timeout: 5m
  go: "1.25"
  tests: false

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gosec
    - revive

formatters:
  enable:
    - gofmt

issues:
  new-from-rev: HEAD~1
